### ISSUE TITLE
Min Vid overlay overlaps website's toolbar on Youtube (new UI) and Vimeo

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#1063]
[Affected versions]:
- Firefox 55.0.3 and up
- Min Vid v.0.4.4

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min Vid add-on version (0.4.4) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to YouTube (www.youtube.com/new).
2. Click on one of the videos. 
3. While hovering the player, scroll down slowly.
4. Observe the website's toolbar while scrolling down the Min Vid overlay.

[Expected result]:
- The Min-Vid overlay is hidden under the toolbar. 

[Actual result]:
- The Min-Vid overlay overlaps website's toolbar.

[Notes]:
- On Youtube's old UI this issue is not reproducible.
- Please see the following screencast of the issue:

![overlay](https://user-images.githubusercontent.com/26000308/30748675-b1690a7a-9fb9-11e7-8cbb-4e16254162e3.gif)

**Comment by meandavejustice** [comment]
fixed in https://github.com/meandavejustice/min-vid/commit/938a1cbf8ecf0fa44e375c6497bf4bad7376dfb2

**Comment by SoftVision-CarmenFat** [comment]
- Tested this with latest Min Vid v.0.4.5 (built on 9/26/2017) and I can confirm that Min Vid's overlay is not overlapping Youtube's toolbar anymore.
- However, the issue is still reproducible on Vimeo's Homepage. 

![vimeo overlay](https://user-images.githubusercontent.com/26000308/30859993-698ef468-a2ce-11e7-8a07-3cbc1660a6d3.gif)
