### ISSUE TITLE
Don't show icon overlay in fullscreen mode

### ISSUE THREAD

**Issue by 6a68** [meandavejustice/min-vid#185]
Easiest fix for this might be a CSS media query to hide the icon above a certain video element size.

**Comment by meandavejustice** [comment]
What do you think about fixing #186 instead of this. Seems like that would get rid of this annoyance. You may still want to send to min vid from the fullscreen view. Although we would need to test this across platforms.

**Comment by meandavejustice** [comment]
fixed in #420

**Comment by chylex** [comment]
Issue is either not fixed or it's reappeared, youtube fullscreen still shows the overlay icons after all other player controls disappear:
![obrazek](https://user-images.githubusercontent.com/3685160/28090367-4f72d1a4-668c-11e7-97a5-1f283ecb4975.png)

**Comment by Silvery-Corgan** [comment]
Happens to me as well in Firefox 55.0.1 x64
