### ISSUE TITLE
Invalid URI warning is diplayed in Browser Console when closing the Min-Vid player

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#438]
**[Affected versions]:**
-Firefox 45.0 and up
-Min-Vid v0.3.1

**[Affected Platforms]:**
-All Windows

**[Prerequisites]:**
-Latest Min-Vid add-on version (0.3.1-dev) was previously installed on a profile.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to a website with videos supported by Min-Vid player (eg: YouTube, Vimeo, etc).
3. Open the Browser Console.
4. Send a video to the mini player.
5. Click on Close "X" button from the player

**[Expected result]:**
-There should be no warnings in the console when closing the Min-Vid player.

**[Actual result]:**
-The following warning message is displayed in the Browser Console when closing the Min-Vid player: `Invalid URI. Load of media resource  failed...default.html`

**[Additional Notes]:**
-Sometimes this error is displayed also when sending the video to Min-Vid player.
-Clicking on the `default.html` link, I'm redirected to: view-source:resource://min-vid/data/default.html?cachebust=1476806451040
-[Here](https://drive.google.com/open?id=0B6QogV2AJFKiWDJrSDBNNVNMMGM) is a video of the issue.

**Comment by 6a68** [comment]
I think this should be fixed by #475

**Comment by SoftVision-EmilPasca** [comment]
The issue is still reproducible on the latest build (0.3.3).

**Comment by meandavejustice** [comment]
@SoftVision-EmilPasca Are we still having this issue?

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest build (0.3.6).
