### ISSUE TITLE
Incorrect Min Vid context menu option appears after saving an image with Page Shot

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [meandavejustice/min-vid#490]
[Affected versions]:
- Firefox 49.0.2 and up
- Min Vid 0.3.3-dev

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- Latest Page Shot add-on version (2.3.201611081751)
- Latest Min Vid add-on version (0.3.3-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Click on the "PageShot" button from browser toolbar and save a selection on the page.
3. Right click anywhere on the image.
4. Observe the last option from the newly opened context menu.

[Expected result]:
- The default context menu options are displayed in it.

[Actual result]:
- An extra "Add-ons" option appears under "Inspect element", witch contains 12 "Send to mini player" options.

[Notes]:
- After saving a shot, if you navigate on Test Pilot website, the extra "Add-ons" option is also displayed on the context menu.
- If another context menu is opened on a different website, the issue is no longer reproducible even if another shot is performed. But, if the browser is restarted, the issue is again reproducible after saving a shot.
- Added a screen recording with the issue:
![min vid contexe menu 4](https://cloud.githubusercontent.com/assets/19226534/20183011/7299d0d6-a76c-11e6-8ffb-0fdb6abbc018.gif)

- Here are the console errors occurred when the context menu is opened: 
 ![browser console context menu](https://cloud.githubusercontent.com/assets/19226534/20183020/78d31066-a76c-11e6-8bc1-91e5535179f5.png)

**Comment by t-kitsune** [comment]
This is the same issue I had

**Comment by johngruen** [comment]
dom no longer captured in Screenshots this should be fixed

**Comment by SoftVision-PaulOiegas** [comment]
Sorry to say but this still occurs even with the Nightly Screenshots version. The strange part is, that it continues to happen until you right click a a supported media. For example I get the wrong context menu until I right click a YouTube video. After that, even where the wrong menu was displayed, you have the normal Min Vid one, and this persists until browser is restarted.

Here is a recording of the issue: https://goo.gl/FgX7j6.
