### ISSUE TITLE
Min-Vid player cannot be closed from "X" button if previously a video was sent to it by clicking the "+" button

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#680]
**[Affected versions]:**
-Firefox 52.0 and up
-Min-Vid 0.3.4-dev (built on 3/20/2017)

**[Affected Platforms]:**
-All Windows
-All Mac
-All Linux

**[Prerequisites]:**
-Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to any supported platform.
2. Send a video/song to the mini player by clicking on the "+" button.
3. Click on "X" button from the Min-Vid player to close the player.

**[Expected result]:**
- Min-Vid player is closed.

**[Actual result]:**
- Min-Vid player cannot be closed. Clicking on the "X" button does nothing.

**Comment by Softvision-VladBacia** [comment]
When I focus the Min-Vid window, in Developer Tools the following error is displayed:
```
Error: Permission denied to access property "target"[Learn More]  bundle.js:22904:7
	getEventTarget resource://min-vid/data/bundle.js:22904:7
	handleTopLevelImpl resource://min-vid/data/bundle.js:17419:27
	perform resource://min-vid/data/bundle.js:21981:13
	batchedUpdates resource://min-vid/data/bundle.js:17110:14
	batchedUpdates resource://min-vid/data/bundle.js:20109:10
	dispatchEvent resource://min-vid/data/bundle.js:17509:7
	bound dispatchEvent
```
and when I click on the "X" close button I get:
```
min-vid:TypeError: Services.appShell.hiddenDOMWindow.navigator.sendBeacon is not a function
Stack trace:
_gaSend@resource://gre/modules/commonjs/toolkit/loader.js -> resource://min-vid/node_modules/testpilot-metrics/testpilot-metrics.js:226:7
sendEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://min-vid/node_modules/testpilot-metrics/testpilot-metrics.js:123:7
sendMetricsData@resource://gre/modules/commonjs/toolkit/loader.js -> resource://min-vid/lib/send-metrics-data.js:26:3
handleMessage@resource://gre/modules/commonjs/toolkit/loader.js -> resource://min-vid/lib/window-utils.js:199:5
pollForCommands@resource://gre/modules/commonjs/toolkit/loader.js -> resource://min-vid/lib/window-utils.js:137:7
notify@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/timers.js:40:9
```
with the *.xpi built on 03/21/2017, I cannot reproduce this issue.

**Comment by meandavejustice** [comment]
@Softvision-VladBacia It looks like this may have been fixed with one of the other issues. I'm not able to reproduce, do you mind verifying?

**Comment by Softvision-VladBacia** [comment]
@meandavejustice , this issue is still happening on my daily profile. I've uninstalled the old Min-Vid version and installed the latest one, restarted the browser and send the first youtube video to the mini player with "+" .

In the Developers Tools Console I see this:
```
Error: Permission denied to access property "target"[Learn More]  bundle.js:23051:7
	getEventTarget resource://min-vid/data/bundle.js:23051:7
	handleTopLevelImpl resource://min-vid/data/bundle.js:17566:27
	perform resource://min-vid/data/bundle.js:22128:13
	batchedUpdates resource://min-vid/data/bundle.js:17257:14
	batchedUpdates resource://min-vid/data/bundle.js:20256:10
	dispatchEvent resource://min-vid/data/bundle.js:17656:7
	bound dispatchEvent
```
and
```
"Handler function DebuggerTransport.prototype.onOutputStreamReady threw an exception: [Exception... "Component returned failure code: 0x80470007 (NS_BASE_STREAM_WOULD_BLOCK) [nsIOutputStream.write]"  nsresult: "0x80470007 (NS_BASE_STREAM_WOULD_BLOCK)"  location: "JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/transport/packets.js :: JSONPacket.prototype.write :: line 198"  data: no]
Stack: JSONPacket.prototype.write@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/transport/packets.js:198:17
DebuggerTransport.prototype.onOutputStreamReady<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/transport/transport.js:279:9
exports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14
Line: 198, column: 0" 1 ThreadSafeDevToolsUtils.js:80

```

**Comment by meandavejustice** [comment]
Still not seeing this, so I'm gunna push it into the `post-queue-release`

**Comment by meandavejustice** [comment]
@6a68 If you have some time, would you mind trying this out? I'm still having trouble reproducing it.

**Comment by Softvision-VladBacia** [comment]
The issue is no longer reproducible on the latest Min Vid v0.3.6-dev built on 4/19/2017.
